name: 'Surge Preview For AntV'
description: 'Preview website in surge.sh for every pull request'
author: 'lxfu1'
inputs:
  surge_token:
    description: 'surge.sh token'
    default: '6973bdb764f0d5fd07c910de27e2d7d0'
  github_token:
    description: 'github token'
    required: true
  project_name:
    description: 'project name'
    default: 'G2Plot'
  project_branch:
    description: 'project branch'
    default: 'master'
  build:
    description: 'build scripts'
    default: |
      mkdir -p pub/preview
      npm install
    required: false
  dist:
    description: 'dist folder to deploy'
    default: 'pub/preview'
    required: false
  failOnError:
    description: 'Set `failed` if a deployment throws error'
  teardown:
    description: 'Determines if the preview instance will be torn down on PR close'
    default: 'false'
    required: false
outputs:
  preview_url:
    description: 'The url for the related PR preview'
runs:
  using: node12
  main: 'dist/index.js'
branding:
  icon: 'monitor'
  color: 'yellow'
