name: 'preview'
on: # rebuild any PRs and main branch changes
  pull_request:
    # use default types + closed event type
    types: [opened, synchronize, reopened, closed]

jobs:
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: preview_step
        name: test lxfu1/surge-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_branch: ${GITHUB_REF##*/}
          teardown: 'true'
          dist: pub/preview
          build: |
            mkdir -p pub/preview
            npm install
      - name: Get the output url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
